version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Update and install
          command: |
            sudo apt update && sudo apt install -y openconnect curl ca-certificates
      - run:
          name: VPN Connection
          command: |
            echo "Conectando a VPN..."
            nohup sudo openconnect --protocol=gp --user=${VPN_USER} --passwd-on-stdin vpn.ull.es > vpn.log 2>&1 < /dev/null &
            echo $! > vpn.pid
            timeout=0
            while ! ip a show tun0 &>/dev/null && [ $timeout -lt 60 ]; do
              echo "Esperando conexión VPN..."
              sleep 1
              timeout=$((timeout+1))
            done
            if [ $timeout -ge 60 ]; then
              echo "No se pudo conectar a la VPN en 60 segundos."
              cat vpn.log
              exit 1
            fi
            echo "VPN conectada"
            curl -s http://checkip.amazonaws.com
      - run:
          name: Run commands in our infrastructure
          command: |
            echo "Public IP is now ..."
            curl -s http://checkip.amazonaws.com
            echo "Done"
            # Another command
      - run:
        name: Disconnect from VPN
        command: |
          if [ -f vpn.pid ]; then
            sudo kill -2 $(cat vpn.pid) || true
            rm vpn.pid
          else
            echo "No se encontró vpn.pid"
          fi
        when: always



